spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1
      file-size-threshold: -1
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:33060/railway #jdbc:mysql://monorail.proxy.rlwy.net:55053/railway
    username: root
    password: root #4DDegac1e4EHeHAFEcaDfA2GhhAcfCgd
  application:
    name: ciudadania

#logging.level:
  #org.hibernate.SQL: DEBUG
  #org.hibernate.type.descriptor.sql: TRACE
  #BasicBinder=TRACE


